apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zfs-csi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mike-homelab/homelab-k8s-platform
    targetRevision: main
    path: infra/zfs-csi
  destination:
    server: https://kubernetes.default.svc
    namespace: zfs-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
