apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-token
  namespace: infra
type: Opaque
stringData:
  token: "PeyJhIjoiODFkMTc3ZGYwZjdjNjA3Y2JiOTc4YzM2YmRkYmFiZjgiLCJ0IjoiZTlmNmZkOWMtOTFiOS00MGRiLTk2NjgtZGJiYjU1Zjc2OGU4IiwicyI6Ik1qRTFPV1U0T1dFdE9UVm1PUzAwWTJaaUxUazNPVEV0WmpSaE9HTTNNR1kwWTJZNCJ9"