---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-cluster-issuer
spec:
  vault:
    server: "https://vault.michaelhomelab.work:8200"
    path: pki_int/issue/michaelhomelab-cluster
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: michaelhomelab-cluster
        serviceAccountRef:
          name: cert-manager

