apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zfs-csi-node
  namespace: zfs-csi
spec:
  selector:
    matchLabels:
      app: zfs-csi-node
  template:
    metadata:
      labels:
        app: zfs-csi-node
    spec:
      serviceAccountName: zfs-csi-sa
      containers:
        - name: zfs-plugin
          image: openebs/zfs-driver:2.6.0
          securityContext:
            privileged: true
          args:
            - "--endpoint=unix:///csi/csi.sock"
            - "--nodename=$(KUBE_NODE_NAME)"
            - "--plugin=node"
            - "--name=zfs.csi.openebs.io"
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /var/lib/kubelet
              name: kubelet-dir
              mountPropagation: Bidirectional
            - mountPath: /dev
              name: device-dir
            - mountPath: /run
              name: run-dir
            - mountPath: /etc/udev
              name: udev-dir
            - mountPath: /csi
              name: socket-dir
      volumes:
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
        - name: run-dir
          hostPath:
            path: /run
        - name: udev-dir
          hostPath:
            path: /etc/udev
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/zfs.csi.openebs.io
            type: DirectoryOrCreate
