apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kito
  namespace: argocd
spec:
  project: ai-application
  source:
    repoURL: https://github.com/mike-homelab/homelab-k8s-platform
    targetRevision: main
    path: clusters/homelab/apps/ai-application/kito
  destination:
    server: https://kubernetes.default.svc
    namespace: kito
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
