apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: watchtower
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  project: ai-application
  source:
    repoURL: https://github.com/mike-homelab/homelab-k8s-platform
    targetRevision: main
    path: clusters/homelab/apps/ai-application/watchtower
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
