apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-crds
  namespace: argocd
spec:
  project: platform

  source:
    repoURL: git@github.com:mike-homelab/homelab-k8s-platform.git
    targetRevision: main
    path: infrastructure/crd

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
