apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-crds
  namespace: argocd
spec:
  project: platform

  source:
    repoURL: https://github.com/mike-homelab/homelab-k8s-platform
    targetRevision: main
    path: infrastructure/metallb

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd   # namespace irrelevant for CRDs

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
