apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: 0.9.2
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/mike-homelab/homelab-k8s-platform/main/clusters/homelab/infra/monitoring/alloy-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
