apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dataprepper
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: monitoring

  source:
    repoURL: https://opensearch-project.github.io/helm-charts
    chart: data-prepper
    targetRevision: "0.3.1"
    helm:
      values: |
        replicaCount: 1
        pipelineConfig:
          enabled: true
          existingSecret: dataprepper-pipelines

        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            memory: 1Gi

        extraEnvs:
          - name: OPENSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: opensearch-admin
                key: password

        volumes:
          - name: opensearch-ca
            secret:
              secretName: opensearch-tls
              items:
                - key: ca.crt
                  path: opensearch-ca.crt

        volumeMounts:
          - name: opensearch-ca
            mountPath: /usr/share/data-prepper/config/opensearch-ca.crt
            subPath: opensearch-ca.crt
            readOnly: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
