apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: monitoring

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: "10.5.15"
    helm:
      values: |
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 512Mi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
