apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-stack
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: lgtm-distributed
    targetRevision: 3.0.1
    helm:
      values: |
        global:
          storageClass: "zfs-nvme"
          minio:
            enabled: true
            replicas: 1
            persistence:
              size: 50Gi
            # MINIO LIFECYCLE: Forces 30-day deletion even if apps fail
            defaultBuckets:
              - name: chunks
                policy: none
                purge: false
                lifecycle:
                  - id: cleanup-30d
                    enabled: true
                    expiration:
                      days: 30
              - name: mimir
                lifecycle:
                  - id: cleanup-30d
                    enabled: true
                    expiration:
                      days: 30
              - name: tempo
                lifecycle:
                  - id: cleanup-30d
                    enabled: true
                    expiration:
                      days: 30

        loki:
          deploymentMode: SimpleScalable
          loki:
            auth_enabled: false
            commonConfig:
              replication_factor: 1
            storage:
              type: s3
              s3:
                endpoint: lgtm-stack-minio.monitoring.svc.cluster.local:9000
                bucketnames: chunks
                access_key_id: enterprise-logs
                secret_access_key: supersecret
                s3forcepathstyle: true
                insecure: true
            limits_config:
              retention_period: 720h # 30 Days
          # Required: Compactors handle the logic of "marking" data for deletion
          compactor:
            enabled: true
            retention_enabled: true
          read: { replicas: 1, resources: { requests: { cpu: 10m, memory: 128Mi } } }
          write: { replicas: 1, resources: { requests: { cpu: 10m, memory: 256Mi } } }
          backend: { replicas: 1 }

        mimir:
          mimir:
            structuredConfig:
              common:
                storage:
                  backend: s3
                  s3:
                    endpoint: lgtm-stack-minio.monitoring.svc.cluster.local:9000
                    access_key_id: enterprise-logs
                    secret_access_key: supersecret
                    insecure: true
                    bucket_name: mimir
              limits:
                compactor_blocks_retention_period: 30d
              multitenancy_enabled: false
          distributor: { replicas: 1 }
          ingester: { replicas: 1, persistence: { size: 10Gi } }
          querier: { replicas: 1 }
          query_frontend: { replicas: 1 }
          compactor: { replicas: 1 }
          store_gateway: { replicas: 1 }
          minio: { enabled: false }

        tempo:
          tempo:
            storage:
              trace:
                backend: s3
                s3:
                  bucket: tempo
                  endpoint: lgtm-stack-minio.monitoring.svc.cluster.local:9000
                  access_key_id: enterprise-logs
                  secret_access_key: supersecret
                  insecure: true
                block:
                  retention: 720h # 30 Days
          distributor: { replicas: 1 }
          ingester: { replicas: 1 }
          querier: { replicas: 1 }
          compactor: { replicas: 1 }

        grafana:
          persistence:
            enabled: true
            storageClass: "zfs-ssd"
            size: 2Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true