apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-stack
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: lgtm-distributed
    targetRevision: 3.0.1
    helm:
      values: |
        # --- GRAFANA SECTION (Aligned with your snippet) ---
        grafana:
          enabled: true
          persistence:
            enabled: true
            storageClassName: "zfs-ssd"
            size: 2Gi
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: Loki
                  uid: loki
                  type: loki
                  url: http://{{ .Release.Name }}-loki-gateway
                - name: Mimir
                  uid: prom
                  type: prometheus
                  url: http://{{ .Release.Name }}-mimir-nginx/prometheus
                  isDefault: true
                - name: Tempo
                  uid: tempo
                  type: tempo
                  url: http://{{ .Release.Name }}-tempo-query-frontend:3200

        # --- LOKI SECTION (Added Storage logic to sub-chart) ---
        loki:
          enabled: true
          loki:
            storage:
              type: s3
              s3:
                endpoint: lgtm-stack-mimir-minio.monitoring.svc.cluster.local:9000
                bucketnames: chunks
                access_key_id: mimir
                secret_access_key: supersecret
                s3forcepathstyle: true
                insecure: true

        # --- MIMIR SECTION (Strictly Aligned with your Resources & Replicas) ---
        mimir:
          enabled: true
          alertmanager: { resources: { requests: { cpu: 20m } } }
          compactor: { resources: { requests: { cpu: 20m } } }
          distributor: { resources: { requests: { cpu: 20m } } }
          ingester:
            replicas: 2
            zoneAwareReplication: { enabled: false }
            resources: { requests: { cpu: 20m } }
            persistentVolume: { storageClass: "zfs-nvme", size: 10Gi }
          overrides_exporter: { resources: { requests: { cpu: 20m } } }
          querier: { replicas: 1, resources: { requests: { cpu: 20m } } }
          query_frontend: { resources: { requests: { cpu: 20m } } }
          query_scheduler: { replicas: 1, resources: { requests: { cpu: 20m } } }
          ruler: { resources: { requests: { cpu: 20m } } }
          store_gateway:
            zoneAwareReplication: { enabled: false }
            resources: { requests: { cpu: 20m } }
          rollout_operator: { resources: { requests: { cpu: 20m } } }
          
          # Enabling the minio sub-component from your snippet
          minio:
            enabled: true
            resources: { requests: { cpu: 20m } }
            persistence: { enabled: true, storageClass: "zfs-nvme", size: 50Gi }

          # Injecting configuration to the Mimir sub-chart binary
          mimir:
            structuredConfig:
              common:
                storage:
                  backend: s3
                  s3:
                    endpoint: lgtm-stack-mimir-minio.monitoring.svc.cluster.local:9000
                    access_key_id: mimir
                    secret_access_key: supersecret
                    insecure: true
                    bucket_name: mimir
              multitenancy_enabled: false

        # --- TEMPO SECTION (Aligned with your snippet) ---
        tempo:
          enabled: true
          ingester:
            replicas: 1

        grafana-oncall:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true