apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-stack
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: lgtm-distributed
    targetRevision: 3.0.1
    helm:
      values: |
        global:
          storageClass: "zfs-nvme"

        # 1. LOKI - Single Binary
        loki:
          deploymentMode: SingleBinary
          loki:
            auth_enabled: false
            commonConfig:
              replication_factor: 1
            storage:
              type: filesystem
          singleBinary:
            replicas: 1
            persistence:
              storageClass: "zfs-nvme"
              size: 20Gi

        # 2. MIMIR - Monolithic Backend Mode
        mimir:
          mimir:
            structuredConfig:
              multitenancy_enabled: false
              common:
                storage:
                  backend: filesystem
              blocks_storage:
                backend: filesystem
              alertmanager_storage:
                backend: filesystem
              ruler_storage:
                backend: filesystem
          minio:
            enabled: false 
          # Disable all distributed micro-components
          ingester: { replicas: 0 }
          querier: { replicas: 0 }
          distributor: { replicas: 0 }
          compactor: { replicas: 0 }
          store_gateway: { replicas: 0 }
          # Use the monolithic backend (this replaces all the above)
          backend:
            replicas: 1
            persistentVolume:
              storageClass: "zfs-nvme"
              size: 20Gi

        # 3. TEMPO - Monolithic
        tempo:
          fullnameOverride: tempo
          tempo:
            replicas: 1
            storage:
              trace:
                backend: local
          persistence:
            enabled: true
            storageClass: "zfs-nvme"
            size: 20Gi
          # Explicitly disable distributed parts
          ingester: { enabled: false }
          distributor: { enabled: false }
          querier: { enabled: false }
          queryFrontend: { enabled: false }
          compactor: { enabled: false }

        # 4. GRAFANA
        grafana:
          enabled: true
          persistence:
            enabled: true
            storageClass: "zfs-ssd"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true