apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-stack
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: lgtm-distributed
    targetRevision: 3.0.1 # Updated to the latest stable major version
    helm:
      values: |
        global:
          storageClass: "zfs-ssd"

        # 1. LOKI (Logs) - Modern 3.0+ Config
        loki:
          deploymentMode: SingleBinary
          loki:
            auth_enabled: false
            commonConfig:
              replication_factor: 1
          singleBinary:
            replicas: 1
            persistence:
              storageClass: "zfs-nvme"
              size: 20Gi

        # 2. TEMPO (Traces)
        tempo:
          fullnameOverride: tempo
          tempo:
            replicas: 1
          persistence:
            enabled: true
            storageClass: "zfs-nvme"

        # 3. MIMIR (Metrics)
        mimir:
          mimir:
            structuredConfig:
              multitenancy_enabled: false
              common:
                replication_factor: 1
          # In v3.x of the umbrella chart, monolithic is often 'backend' or 'mimir'
          backend:
            replicas: 1
            persistentVolume:
              storageClass: "zfs-nvme"

        # 4. GRAFANA
        grafana:
          enabled: true
          persistence:
            enabled: true
            storageClass: "zfs-ssd"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true