apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-stack
  namespace: argocd
spec:
  project: monitoring # Matches your 'argocd app get' output
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: lgtm-distributed
    targetRevision: 3.0.1
    helm:
      values: |
        global:
          storageClass: "zfs-nvme"

        loki:
          deploymentMode: SingleBinary
          singleBinary:
            replicas: 1
            persistence:
              enabled: true
              size: 20Gi

        mimir:
          deploymentMode: SingleBinary
          mimir:
            structuredConfig:
              common:
                storage:
                  backend: filesystem
              blocks_storage:
                backend: filesystem
          # Force disable all microservices
          minio: { enabled: false }
          ingester: { replicas: 0 }
          querier: { replicas: 0 }
          distributor: { replicas: 0 }
          compactor: { replicas: 0 }
          store_gateway: { replicas: 0 }
          alertmanager: { replicas: 0 }
          backend: { replicas: 1 } # This is the single binary pod

        tempo:
          fullnameOverride: tempo
          tempo:
            replicas: 1
          persistence:
            enabled: true
            size: 20Gi

        grafana:
          enabled: true
          persistence:
            enabled: true
            storageClass: "zfs-ssd"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - PrunePropagationPolicy=foreground