apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-stack
  namespace: argocd
spec:
  project: monitoring
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec/volumeName
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: lgtm-distributed
    targetRevision: 3.0.1
    helm:
      values: |
        # --- GRAFANA ---
        grafana:
          enabled: true
          persistence:
            enabled: true
            storageClassName: "zfs-ssd"
            size: 2Gi
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: Loki
                  uid: loki
                  type: loki
                  url: http://{{ .Release.Name }}-loki-gateway
                - name: Mimir
                  uid: prom
                  type: prometheus
                  url: http://{{ .Release.Name }}-mimir-nginx/prometheus
                  isDefault: true
                - name: Tempo
                  uid: tempo
                  type: tempo
                  url: http://{{ .Release.Name }}-tempo-query-frontend:3200

        # --- LOKI (Proven Working) ---
        loki:
          enabled: true
          loki:
            storage:
              type: s3
              s3:
                endpoint: 10.0.0.13:3900
                bucketnames: lgtm-loki
                access_key_id: GKa978bde4134534803e5dcf2d
                secret_access_key: e48a7520f58171007fd47b89f66ab8d029d60e0bcf7411e336091af0fc029e39
                s3forcepathstyle: true
                insecure: true

        # --- MIMIR (The Argument Override Fix) ---
        mimir:
          enabled: true
          # We don't touch the MinIO setting because it's a hard dependency
          
          # Force Mimir to use Garage via Command Line Arguments
          mimir:
            extraArgs:
              - "-common.storage.backend=s3"
              - "-common.storage.s3.endpoint=10.0.0.13:3900"
              - "-common.storage.s3.access-key-id=GKa978bde4134534803e5dcf2d"
              - "-common.storage.s3.secret-access-key=e48a7520f58171007fd47b89f66ab8d029d60e0bcf7411e336091af0fc029e39"
              - "-common.storage.s3.insecure=true"
              - "-blocks-storage.s3.bucket-name=lgtm-mimir"
              - "-alertmanager-storage.s3.bucket-name=lgtm-mimir"
              - "-ruler-storage.s3.bucket-name=lgtm-mimir"
          
          # Maintain your CPU and Replica requirements
          alertmanager: { resources: { requests: { cpu: 20m } } }
          compactor: { resources: { requests: { cpu: 20m } } }
          distributor: { resources: { requests: { cpu: 20m } } }
          ingester:
            replicas: 2
            resources: { requests: { cpu: 20m } }
            persistentVolume: { storageClass: "zfs-nvme", size: 10Gi }
          overrides_exporter: { resources: { requests: { cpu: 20m } } }
          querier: { replicas: 1, resources: { requests: { cpu: 20m } } }
          query_frontend: { resources: { requests: { cpu: 20m } } }
          query_scheduler: { replicas: 1, resources: { requests: { cpu: 20m } } }
          ruler: { resources: { requests: { cpu: 20m } } }
          store_gateway: { resources: { requests: { cpu: 20m } } }
          rollout_operator: { resources: { requests: { cpu: 20m } } }

        # --- TEMPO ---
        tempo:
          enabled: true
          ingester: { replicas: 1 }
          storage:
            trace:
              backend: s3
              s3:
                endpoint: 10.0.0.13:3900
                bucket: lgtm-tempo
                access_key: GKa978bde4134534803e5dcf2d
                secret_key: e48a7520f58171007fd47b89f66ab8d029d60e0bcf7411e336091af0fc029e39
                insecure: true

        grafana-oncall:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true