apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.51.0"
    helm:
      values: |
        deploymentMode: SimpleScalable
        
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          limits_config:
            retention_period: 168h
            deletion_mode: filter-and-delete
          compactor:
            retention_enabled: true
            delete_request_store: s3
            working_directory: /var/loki/compactor
            compaction_interval: 10m
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: index_
                  period: 24h
          storage:
            type: s3
            bucketNames:
              chunks: loki-chunks
              ruler: loki-ruler
              admin: loki-admin
            s3:
              endpoint: minio.monitoring.svc:9000
              accessKeyId: QNm0d2hHLBGhjKVS28N3
              secretAccessKey: juw4e9AqlpQQvHWfKWO4BoUiLS37MQ2BMk7LFq4Q
              s3ForcePathStyle: true
              insecure: true
              region: us-east-1

        chunksCache:
          allocatedMemory: 512
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
        resultsCache:
          allocatedMemory: 512
          resources:
            requests:
              cpu: 100m
              memory: 512Mi

        backend:
          replicas: 1
          persistence:
            size: 10Gi
            storageClass: "zfs-nvme"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
        read:
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
        write:
          replicas: 1
          persistence:
            size: 10Gi
            storageClass: "zfs-nvme"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
        gateway:
          replicas: 1
        minio:
          enabled: false
        singleBinary:
          replicas: 0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true