apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.24.0"
    helm:
      values: |
        deploymentMode: SingleBinary
        
        loki:
          auth_enabled: false
          
          # Mandatory for Loki 3.x
          commonConfig:
            replication_factor: 1

          # Mandatory: Defines how to write to your buckets
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: index_
                  period: 24h

          storage:
            type: s3
            bucketNames:
              chunks: loki-chunks
              ruler: loki-ruler
              admin: loki-admin
            s3:
              endpoint: minio.monitoring.svc:9000
              accessKeyId: m67h762Pb9OkmQUpEAam
              secretAccessKey: ics2xjKfIyoWl5i0I54iSeRw8apYbi9XvnefKcse
              s3ForcePathStyle: true
              insecure: true

        minio:
          enabled: false

        # Resource tuning for Single Binary mode
        singleBinary:
          replicas: 1
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true