apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-s3
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.24.0
    helm:
      values: |
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: s3
            s3:
              endpoint: 10.0.0.13:3900
              access_key_id: GKa978bde4134534803e5dcf2d
              secret_access_key: e48a7520f58171007fd47b89f66ab8d029d60e0bcf7411e336091af0fc029e39
              s3forcepathstyle: true
              insecure: true
              bucketnames: lgtm-loki
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: index_
                  period: 24h
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            storageClass: "zfs-ssd"
            size: 10Gi
        gateway:
          enabled: false
        minio:
          enabled: false
        # The agent that actually grabs the logs from your nodes
        promtail:
          enabled: true
          config:
            clients:
              - url: http://loki-s3:3100/loki/api/v1/push
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]