apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.51.0"
    helm:
      values: |
        deploymentMode: SimpleScalable
        
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          
          # 1. Define the Global Retention Period
          limits_config:
            retention_period: 168h # 7 days (7 * 24h)
            allow_deletes: true

          # 2. Enable the Compactor to enforce the limits
          compactor:
            retention_enabled: true
            delete_request_store: s3
            working_directory: /var/loki/compactor
            compaction_interval: 10m

          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: index_
                  period: 24h
          
          storage:
            type: s3
            bucketNames:
              chunks: loki-chunks
              ruler: loki-ruler
              admin: loki-admin
            s3:
              endpoint: minio.monitoring.svc:9000
              accessKeyId: m67h762Pb9OkmQUpEAam
              secretAccessKey: ics2xjKfIyoWl5i0I54iSeRw8apYbi9XvnefKcse
              s3ForcePathStyle: true
              insecure: true

        # Component Resources & Scaling
        backend:
          replicas: 1
          persistence:
            size: 10Gi
            storageClass: "zfs-nvme"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
        read:
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
        write:
          replicas: 1
          persistence:
            size: 10Gi
            storageClass: "zfs-nvme"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi

        gateway:
          replicas: 1
          resources:
            requests:
              cpu: 50m
              memory: 64Mi

        minio:
          enabled: false
        singleBinary:
          replicas: 0

  syncPolicy:
    automated:
      prune: true
      selfHeal: true