apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: monitoring

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "*"
    helm:
      values: |
        deploymentMode: SingleBinary

        singleBinary:
          replicas: 1
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi

        # 🔴 REQUIRED: disable scalable components
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0

        loki:
          auth_enabled: false

          commonConfig:
            replication_factor: 1

          storage:
            type: filesystem

          schemaConfig:
            configs:
              - from: 2024-01-01
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h

          storage_config:
            filesystem:
              directory: /var/loki/chunks

          compactor:
            working_directory: /var/loki/compactor
            retention_enabled: true

          limits_config:
            retention_period: 168h
            allow_structured_metadata: true

        persistence:
          enabled: true
          storageClassName: zfs-ssd
          size: 50Gi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
