apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-s3
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.24.0
    helm:
      values: |
        deploymentMode: SingleBinary
        
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          
          storage:
            type: s3
            s3:
              endpoint: 10.0.0.13:3900
              access_key_id: GKa978bde4134534803e5dcf2d
              secret_access_key: e48a7520f58171007fd47b89f66ab8d029d60e0bcf7411e336091af0fc029e39
              s3forcepathstyle: true
              insecure: true
            
            # This is the exact block required to pass Helm validation
            # without forcing custom logic.
            bucketNames:
              chunks: lgtm-loki
              ruler: lgtm-loki
              admin: lgtm-loki

        # 100% supported: disable internal Minio to use Garage
        minio:
          enabled: false

        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            storageClass: "zfs-ssd"
            size: 10Gi
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]