apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: monitoring

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "*"
    helm:
      values: |
        minio:
          enabled: false

        loki:
          storage:
            type: s3
            s3:
              endpoint: minio.monitoring.svc:9000
              bucketNames:
                chunks: loki-chunks
                ruler: loki-ruler
                admin: loki-admin
              accessKeyId: minio
              secretAccessKey: minio123
              s3ForcePathStyle: true
              insecure: true

        # Only resource tuning
        singleBinary:
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
