apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: monitoring

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.24.0"
    helm:
      values: |
        minio:
          enabled: false

        loki:
          storage:
            type: s3
            bucketNames:
              chunks: loki-chunks
              ruler: loki-ruler
              admin: loki-admin
            s3:
              endpoint: minio.monitoring.svc:9000
              accessKeyId: pifu2sbv5zC5Ln9q4OIUm
              secretAccessKey: cbfpsCNBlrM8ZNoUBpBPwqTPq5LwX7O3RoNvjhCt
              s3ForcePathStyle: true
              insecure: true

        # Only resource tuning
        singleBinary:
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
