apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: monitoring

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: "*"
    helm:
      values: |
        mode: standalone

        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi

        persistence:
          enabled: true
          storageClass: zfs-nvme
          size: 100Gi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
