apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: mimir-distributed
    targetRevision: "6.0.2"
    helm:
      values: |
        minio:
          enabled: false

        mimir:
          structuredConfig:
            common:
              storage:
                backend: s3
                s3:
                  endpoint: minio.monitoring.svc:9000
                  access_key_id: m67h762Pb9OkmQUpEAam
                  secret_access_key: ics2xjKfIyoWl5i0I54iSeRw8apYbi9XvnefKcse
                  insecure: true

            # Separate buckets for each component to avoid validation errors
            blocks_storage:
              s3:
                bucket_name: mimir-blocks
            
            alertmanager_storage:
              s3:
                bucket_name: mimir-alertmanager
            
            ruler_storage:
              s3:
                bucket_name: mimir-ruler

        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true