apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: mimir-distributed
    targetRevision: "6.0.2"
    helm:
      values: |
        # 1. Official Storage Config (External MinIO)
        minio:
          enabled: false

        mimir:
          structuredConfig:
            common:
              storage:
                backend: s3
                s3:
                  endpoint: minio.monitoring.svc:9000
                  access_key_id: QNm0d2hHLBGhjKVS28N3
                  secret_access_key: juw4e9AqlpQQvHWfKWO4BoUiLS37MQ2BMk7LFq4Q
                  insecure: true
            
            blocks_storage:
              s3:
                bucket_name: mimir-blocks
            alertmanager_storage:
              s3:
                bucket_name: mimir-alertmanager
            ruler_storage:
              s3:
                bucket_name: mimir-ruler

        # 2. Official Resource Controls (Scaling for 3-Worker setup)
        # We use 'replicas: 3' to match your 3 worker nodes.
        ingester:
          replicas: 3
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1Gi
          persistence:
            size: 10Gi
            storageClass: "zfs-nvme"

        store_gateway:
          replicas: 3
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          persistence:
            size: 10Gi
            storageClass: "zfs-nvme"

        distributor:
          replicas: 2
          resources:
            requests:
              cpu: 100m
              memory: 256Mi

        querier:
          replicas: 2
          resources:
            requests:
              cpu: 100m
              memory: 512Mi

        compactor:
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 512Mi

        # 3. Disable internal dependencies you aren't using
        continuous-test:
          enabled: false
        mimir-proxies:
          enabled: false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true