apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://github.com/mike-homelab/homelab-k8s-platform.git
    targetRevision: main
    path: clusters/homelab/apps/monitoring/observability-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
