apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
spec:
  project: monitoring

  source:
    repoURL: oci://ghcr.io/opensearch-project/helm-charts
    chart: opensearch
    targetRevision: 2.30.0
    helm:
      values: |
        clusterName: homelab-opensearch
        singleNode: false

        master:
          replicas: 1
          persistence:
            enabled: false
          opensearchJavaOpts: "-Xms256m -Xmx256m"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

        data:
          replicas: 2
          persistence:
            enabled: true
            size: 100Gi
            storageClass: zfs-nvme
          opensearchJavaOpts: "-Xms1g -Xmx1g"
          resources:
            requests:
              cpu: 300m
              memory: 1Gi
            limits:
              cpu: 2
              memory: 2Gi

        ingest:
          replicas: 0
        coordinating:
          replicas: 0

        securityConfig:
          enabled: true
          tls:
            http:
              enabled: true
              secret: opensearch-tls
            transport:
              enabled: true
              secret: opensearch-tls

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
