apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  project: monitoring

  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.92.0
    helm:
      values: |
        image:
          repository: otel/opentelemetry-collector-contrib
          tag: 0.93.0

        # REQUIRED for pod log collection
        mode: daemonset

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 512Mi

        # Disable presets – explicit config only
        presets:
          logsCollection:
            enabled: false
          hostMetrics:
            enabled: false
          kubeletMetrics:
            enabled: false
          kubernetesAttributes:
            enabled: false

        # Host access to pod logs
        extraVolumes:
          - name: varlogpods
            hostPath:
              path: /var/log/pods
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers

        extraVolumeMounts:
          - name: varlogpods
            mountPath: /var/log/pods
            readOnly: true
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true

        config:
          receivers:
            filelog:
              include:
                - /var/log/pods/*/*/*.log
              start_at: end
              include_file_path: true
              include_file_name: false

          processors:
            k8sattributes:
              auth_type: serviceAccount
              extract:
                metadata:
                  - k8s.namespace.name
                  - k8s.pod.name
                  - k8s.container.name
                  - k8s.node.name
            batch: {}

          exporters:
            otlp/data-prepper:
              endpoint: dataprepper.monitoring.svc.cluster.local:21890
              tls:
                insecure: true

          service:
            pipelines:
              logs:
                receivers: [filelog]
                processors: [k8sattributes, batch]
                exporters: [otlp/data-prepper]

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
