apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  project: monitoring

  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.92.0
    helm:
      values: |
        image:
          repository: otel/opentelemetry-collector-contrib
          tag: 0.93.0

        mode: deployment

        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            memory: 1Gi

        # IMPORTANT: disable implicit receivers
        presets:
          logsCollection:
            enabled: false
          hostMetrics:
            enabled: false
          kubeletMetrics:
            enabled: false
          kubernetesAttributes:
            enabled: false

        config:
          receivers:
            prometheusremotewrite:
              endpoint: 0.0.0.0:9201

          processors:
            batch: {}

          exporters:
            otlp/data-prepper:
              endpoint: data-prepper.monitoring.svc.cluster.local:21890
              tls:
                insecure: true

          service:
            pipelines:
              metrics:
                receivers: [prometheusremotewrite]
                processors: [batch]
                exporters: [otlp/data-prepper]

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
