apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  project: monitoring

  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.92.0
    helm:
      values: |
        image:
          repository: otel/opentelemetry-collector-contrib
          tag: 0.93.0

        # REQUIRED: node-level log collection
        mode: daemonset

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 512Mi

        # Disable presets – explicit pipelines only
        presets:
          logsCollection:
            enabled: false
          hostMetrics:
            enabled: false
          kubeletMetrics:
            enabled: false
          kubernetesAttributes:
            enabled: false

        ############################
        # Volumes (containerd-safe)
        ############################
        extraVolumes:
          - name: varlogpods
            hostPath:
              path: /var/log/pods
          - name: varlogcontainers
            hostPath:
              path: /var/log/containers

        extraVolumeMounts:
          - name: varlogpods
            mountPath: /var/log/pods
            readOnly: true
          - name: varlogcontainers
            mountPath: /var/log/containers
            readOnly: true

        ############################
        # OpenTelemetry Config
        ############################
        config:
          receivers:
            # Pod logs
            filelog:
              include:
                - /var/log/pods/*/*/*.log
              start_at: end
              include_file_path: true
              operators:
                - type: json_parser
                  id: containerd
                  parse_from: body
                  if: 'body matches "^\\{"'

            # Traces from apps (OTLP)
            otlp:
              protocols:
                grpc: {}
                http: {}

          processors:
            k8sattributes:
              auth_type: serviceAccount
              extract:
                metadata:
                  - k8s.namespace.name
                  - k8s.pod.name
                  - k8s.container.name
                  - k8s.node.name
            batch:
              timeout: 5s
              send_batch_size: 1024

          exporters:
            otlp/dataprepper:
              endpoint: dataprepper-data-prepper.monitoring.svc.cluster.local:21890
              tls:
                insecure: true

          service:
            pipelines:
              logs:
                receivers: [filelog]
                processors: [k8sattributes, batch]
                exporters: [otlp/dataprepper]

              traces:
                receivers: [otlp]
                processors: [k8sattributes, batch]
                exporters: [otlp/dataprepper]

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
