apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.111.0 
    helm:
      values: |
        mode: deployment
        replicaCount: 1

        image:
          repository: "otel/opentelemetry-collector-k8s"
          tag: "latest"
          pullPolicy: IfNotPresent

        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi

        config:
          receivers:
            otlp:
              protocols:
                grpc:
                http:

          processors:
            memory_limiter:
              check_interval: 1s
              limit_percentage: 75
              spike_limit_percentage: 15
            batch:
            k8sattributes:
              extract:
                metadata:
                  - k8s.pod.name
                  - k8s.namespace.name
                  - k8s.node.name
              pod_association:
                - sources:
                    - from: resource_attribute
                      name: k8s.pod.ip
                - sources:
                    - from: connection

          exporters:
            otlphttp/loki:
              endpoint: http://loki-gateway.monitoring.svc.cluster.local/otlp

            otlphttp/mimir:
              endpoint: http://mimir-gateway.monitoring.svc.cluster.local/otlp

            otlp/tempo:
              endpoint: tempo-distributor.monitoring.svc.cluster.local:4317
              tls:
                insecure: true

          service:
            pipelines:
              logs:
                receivers: [otlp]
                processors: [k8sattributes, memory_limiter, batch]
                exporters: [otlphttp/loki]

              metrics:
                receivers: [otlp]
                processors: [k8sattributes, memory_limiter, batch]
                exporters: [otlphttp/mimir]

              traces:
                receivers: [otlp]
                processors: [k8sattributes, memory_limiter, batch]
                exporters: [otlp/tempo]


  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true