apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo-distributed
    targetRevision: "1.20.1"
    helm:
      values: |
        # -----------------------------
        # Storage (MinIO / S3)
        # -----------------------------
        storage:
          trace:
            backend: s3
            s3:
              endpoint: minio.monitoring.svc:9000
              bucket: tempo
              access_key: QNm0d2hHLBGhjKVS28N3
              secret_key: juw4e9AqlpQQvHWfKWO4BoUiLS37MQ2BMk7LFq4Q
              insecure: true

        # -----------------------------
        # Core Tempo Runtime Config
        # (THIS is what Tempo actually reads)
        # -----------------------------
        tempo:
          configOverride: |
            multitenancy_enabled: false

            memberlist:
              join_members:
                - dns+tempo-gossip-ring:7946

            metrics_generator:
              ring:
                kvstore:
                  store: memberlist

              processor:
                service_graphs:
                  enabled: true
                span_metrics:
                  enabled: true

              registry:
                collection_interval: 15s

              storage:
                path: /var/tempo/metrics

        # -----------------------------
        # Scaling & Resources
        # -----------------------------
        ingester:
          replicas: 3
          persistence:
            enabled: true
            size: 10Gi
            storageClass: zfs-nvme
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1Gi

        distributor:
          replicas: 2
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi

        querier:
          replicas: 2
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1Gi

        queryFrontend:
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi

        compactor:
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi

        # -----------------------------
        # Metrics Generator (K8s object)
        # -----------------------------
        metricsGenerator:
          enabled: true
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi

        # -----------------------------
        # Disable embedded MinIO
        # -----------------------------
        minio:
          enabled: false
