apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: monitoring

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo-distributed
    targetRevision: "1.27.1"   # 🔒 PINNED
    helm:
      values: |
        # -----------------------------------
        # Storage (MinIO / S3)
        # -----------------------------------
        storage:
          trace:
            backend: s3
            s3:
              endpoint: minio.monitoring.svc:9000
              bucket: tempo
              access_key: QNm0d2hHLBGhjKVS28N3
              secret_key: juw4e9AqlpQQvHWfKWO4BoUiLS37MQ2BMk7LFq4Q
              insecure: true

        # -----------------------------------
        # Tempo runtime config (LGTM-style)
        # -----------------------------------
        tempo:
          structuredConfig:
            multitenancy_enabled: false

            memberlist:
              join_members:
                - dns+tempo-gossip-ring:7946

            # ✅ Metrics Generator is FIRST-CLASS now
            metrics_generator:
              ring:
                kvstore:
                  store: memberlist

              processor:
                service_graphs:
                  enabled: true
                span_metrics:
                  enabled: true

              registry:
                collection_interval: 15s

              storage:
                path: /var/tempo/metrics

        # -----------------------------------
        # Component scaling (homelab-safe)
        # -----------------------------------
        distributor:
          replicas: 2

        ingester:
          replicas: 3
          persistence:
            enabled: true
            size: 10Gi
            storageClass: zfs-nvme

        querier:
          replicas: 2

        queryFrontend:
          replicas: 1

        compactor:
          replicas: 1

        # -----------------------------------
        # Metrics Generator workload
        # -----------------------------------
        metricsGenerator:
          enabled: true
          replicas: 1

        # -----------------------------------
        # Disable embedded MinIO
        # -----------------------------------
        minio:
          enabled: false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
