apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo-s3
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.10.1
    helm:
      values: |
        tempo:
          storage:
            trace:
              backend: s3
              s3:
                endpoint: 10.0.0.13:3900
                bucket: lgtm-tempo
                access_key: GKa978bde4134534803e5dcf2d
                secret_key: e48a7520f58171007fd47b89f66ab8d029d60e0bcf7411e336091af0fc029e39
                insecure: true
          persistence:
            enabled: true
            storageClass: "zfs-ssd"
            size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]