apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo-distributed
    targetRevision: "1.20.1"
    helm:
      values: |
        # 1. Official S3 Storage Config
        storage:
          trace:
            backend: s3
            s3:
              endpoint: minio.monitoring.svc:9000
              bucket: tempo
              access_key: qXbN98xI92GQTGY5yP7W
              secret_key: SgHf0RzfMYhEyQNsiAFcczCrNQnyxDThGbNQq1kf
              insecure: true

        # 2. Component Scaling & Resources (3-Node Worker Layout)
        ingester:
          replicas: 3
          persistence:
            enabled: true
            size: 10Gi
            storageClass: "zfs-nvme"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1Gi

        querier:
          replicas: 2
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1Gi

        queryFrontend:
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi

        distributor:
          replicas: 2
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi

        compactor:
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi

        # 3. Disable unneeded features for Homelab
        metricsGenerator:
          enabled: false
        
        # MinIO is external, so ensure the internal one is off
        minio:
          enabled: false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true