apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-settings
  namespace: ai-platform
data:
  settings.yml: |
    use_default_settings: true
    search:
      safe_search: 0
      autocomplete: ""
      formats:
        - html
        - json
    engines:
      - name: duckduckgo
        engine: duckduckgo
      - name: bing
        engine: bing
      - name: brave
        engine: brave
      - name: qwant
        engine: qwant
      - name: google
        engine: google
      - name: wikipedia
        engine: wikipedia
    enabled_plugins:
      - 'Hash plugin'
      - 'Self-contained snippets'
    ui:
      static_use_hash: true
    server:
      port: 8080
      bind_address: "0.0.0.0"
      secret_key: "homelabsearxngkey"
      limiter: false
      image_proxy: false
