---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    server: https://vault.michaelhomelab.work:8200
    path: pki_int/sign/michaelhomelab-cluster
    caBundleSecretRef:
      name: vault-tls-ca
      key: ca.crt
    auth:
      tokenSecretRef:
        name: vault-token
        key: token





