---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-prepper-config
  namespace: monitoring
data:
  pipelines.yaml: |
    entry-pipeline:
      source:
        otlp:
          grpc:
            ssl: false
      sink:
        - pipeline:
            name: "raw-pipeline"
        - pipeline:
            name: "service-map-pipeline"
    raw-pipeline:
      source:
        pipeline:
          name: "entry-pipeline"
      processor:
        - otel_trace_raw:
      sink:
        - stdout:
    service-map-pipeline:
      source:
        pipeline:
          name: "entry-pipeline"
      processor:
        - service_map_stateful:
      sink:
        - stdout:
  data-prepper-config.yaml: |
    ssl: false
    peer_forwarder:
      discovery_mode: dns
      domain_name: "dataprepper.monitoring.svc.cluster.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-prepper
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-prepper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: data-prepper
    spec:
      containers:
        - image: opensearchproject/data-prepper:2.8.0
          name: data-prepper
          env:
            - name: DATA_PREPPER_PIPELINE_CONFIG_FILE
              value: "/etc/data-prepper/pipelines.yaml"
            - name: DATA_PREPPER_CONFIG_FILE
              value: "/etc/data-prepper/data-prepper-config.yaml"
          ports:
            - containerPort: 21890
              name: otlp-grpc
            - containerPort: 4900
              name: metrics
          volumeMounts:
            - name: config-volume
              mountPath: /etc/data-prepper/pipelines.yaml
              subPath: pipelines.yaml
            - name: config-volume
              mountPath: /etc/data-prepper/data-prepper-config.yaml
              subPath: data-prepper-config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: data-prepper-config
---
apiVersion: v1
kind: Service
metadata:
  name: dataprepper
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: data-prepper # MATCHES Deployment label
  ports:
    - name: otlp-grpc
      protocol: TCP
      port: 21890
      targetPort: 21890
    - name: otlp-http
      protocol: TCP
      port: 21891
      targetPort: 21891
    - name: metrics
      protocol: TCP
      port: 4900
      targetPort: 4900