---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-prepper-config
  namespace: monitoring
data:
  data-prepper-config.yaml: |
    ssl: false
    peer_forwarder:
      discovery_mode: dns
      domain_name: "dataprepper.monitoring.svc.cluster.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-prepper
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-prepper
  template:
    metadata:
      labels:
        app: data-prepper
    spec:
      containers:
      - name: data-prepper
        image: opensearchproject/data-prepper:2.8.0
        # NO command, NO args. Let it use the same entrypoint as Docker Compose.
        env:
          - name: OPENSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: opensearch-admin
                key: password
        volumeMounts:
          # Mount the WHOLE directory, not a subpath
          - name: pipeline-volume
            mountPath: /usr/share/data-prepper/pipelines
          - name: config-volume
            mountPath: /usr/share/data-prepper/config/data-prepper-config.yaml
            subPath: data-prepper-config.yaml
          - name: opensearch-ca
            mountPath: /etc/opensearch-certs/ca.crt
            subPath: ca.crt
      volumes:
        - name: pipeline-volume
          secret:
            secretName: dataprepper-pipelines # Ensure this secret has a key named "pipelines.yaml"
        - name: config-volume
          configMap:
            name: data-prepper-config
        - name: opensearch-ca
          secret:
            secretName: opensearch-tls
---
apiVersion: v1
kind: Service
metadata:
  name: dataprepper
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: data-prepper
  ports:
    - name: otlp-grpc
      port: 21890
      targetPort: 21890
    - name: metrics
      port: 4900
      targetPort: 4900