apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-prepper
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-prepper
  template:
    metadata:
      labels:
        app: data-prepper
    spec:
      containers:
      - name: data-prepper
        image: opensearchproject/data-prepper:2.8.0
        env:
          - name: OPENSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: opensearch-admin
                key: password
        volumeMounts:
          # Mounts the 'pipelines.yaml' key as a file into the /pipelines/ directory
          - name: pipelines-vol
            mountPath: /usr/share/data-prepper/pipelines
          # Mounts the 'data-prepper-config.yaml' key into the /config/ directory
          - name: config-vol
            mountPath: /usr/share/data-prepper/config
          - name: ca-vol
            mountPath: /etc/opensearch-certs
      volumes:
        - name: pipelines-vol
          secret:
            secretName: dataprepper-pipelines
        - name: config-vol
          configMap:
            name: data-prepper-config
        - name: ca-vol
          secret:
            secretName: opensearch-tls