apiVersion: v1
kind: Secret
metadata:
  name: dataprepper-pipelines
  namespace: monitoring
type: Opaque
stringData:
  pipelines.yaml: |
    metrics-pipeline:
      workers: 4
      source:
        prometheus:
          path: /api/v1/write
          ssl: false
      processor:
        - otel_metrics:
        - batch:
      sink:
        - opensearch:
            hosts: ["https://homelab-opensearch.monitoring.svc.cluster.local:9200"]
            username: admin
            password: ${OPENSEARCH_PASSWORD}
            index: metrics-%{yyyy.MM.dd}
            insecure: false
            ssl:
              certificate_authorities: ["/etc/opensearch-certs/ca.crt"]

    logs-pipeline:
      workers: 2
      source:
        otlp:
          logs:
            ssl: false
      processor:
        - batch:
      sink:
        - opensearch:
            hosts: ["https://homelab-opensearch.monitoring.svc.cluster.local:9200"]
            username: admin
            password: ${OPENSEARCH_PASSWORD}
            index: logs-%{yyyy.MM.dd}
            insecure: false
            ssl:
              certificate_authorities: ["/etc/opensearch-certs/ca.crt"]

    traces-pipeline:
      workers: 2
      source:
        otlp:
          traces:
            ssl: false
      processor:
        - batch:
      sink:
        - opensearch:
            hosts: ["https://homelab-opensearch.monitoring.svc.cluster.local:9200"]
            username: admin
            password: ${OPENSEARCH_PASSWORD}
            index: traces-%{yyyy.MM.dd}
            insecure: false
            ssl:
              certificate_authorities: ["/etc/opensearch-certs/ca.crt"]