---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-prepper-config
  namespace: monitoring
data:
  # The filename must match the key exactly for simple mounting
  data-prepper-config.yaml: |
    ssl: false
    peer_forwarder:
      discovery_mode: dns
      domain_name: "dataprepper.monitoring.svc.cluster.local"
---
apiVersion: v1
kind: Secret
metadata:
  name: dataprepper-pipelines
  namespace: monitoring
type: Opaque
stringData:
  # The key name must be 'pipelines.yaml'
  pipelines.yaml: |
    otel-ingest-pipeline:
      workers: 4
      source:
        otlp:
          # Enabling both logs and traces in one source
          grpc:
            ssl: false
          http:
            ssl: false
      sink:
        - opensearch:
            hosts: ["https://homelab-opensearch.monitoring.svc.cluster.local:9200"]
            username: admin
            password: "${env:OPENSEARCH_PASSWORD}"
            index: "otel-v1-%{yyyy.MM.dd}"
            ssl:
              certificate_authorities: ["/etc/opensearch-certs/ca.crt"]

    prometheus-metrics-pipeline:
      source:
        prometheus:
          # Listens for Prometheus remote_write
          path: /api/v1/write
          ssl: false
      sink:
        - opensearch:
            hosts: ["https://homelab-opensearch.monitoring.svc.cluster.local:9200"]
            username: admin
            password: "${env:OPENSEARCH_PASSWORD}"
            index: "metrics-v1-%{yyyy.MM.dd}"
            ssl:
              certificate_authorities: ["/etc/opensearch-certs/ca.crt"]

# apiVersion: v1
# kind: Secret
# metadata:
#   name: dataprepper-pipelines
#   namespace: monitoring
# type: Opaque
# stringData:
#   pipelines.yaml: |
#     metrics-pipeline:
#       workers: 4
#       source:
#         prometheus:
#           path: /api/v1/write
#           ssl: false
#       processor:
#         - otel_metrics:
#         - batch:
#       sink:
#         - opensearch:
#             hosts: ["https://homelab-opensearch.monitoring.svc.cluster.local:9200"]
#             username: admin
#             password: "${OPENSEARCH_PASSWORD}"
#             index: metrics-%{yyyy.MM.dd}
#             insecure: false
#             ssl:
#               certificate_authorities: ["/etc/opensearch-certs/ca.crt"]

#     logs-pipeline:
#       workers: 2
#       source:
#         otlp:
#           logs:
#             ssl: false
#       processor:
#         - batch:
#       sink:
#         - opensearch:
#             hosts: ["https://homelab-opensearch.monitoring.svc.cluster.local:9200"]
#             username: admin
#             password: "${OPENSEARCH_PASSWORD}"
#             index: logs-%{yyyy.MM.dd}
#             insecure: false
#             ssl:
#               certificate_authorities: ["/etc/opensearch-certs/ca.crt"]

#     traces-pipeline:
#       workers: 2
#       source:
#         otlp:
#           traces:
#             ssl: false
#       processor:
#         - batch:
#       sink:
#         - opensearch:
#             hosts: ["https://homelab-opensearch.monitoring.svc.cluster.local:9200"]
#             username: admin
#             password: "${OPENSEARCH_PASSWORD}"
#             index: traces-%{yyyy.MM.dd}
#             insecure: false
#             ssl:
#               certificate_authorities: ["/etc/opensearch-certs/ca.crt"]