---
apiVersion: openebs.io/v1beta3
kind: DiskPool
metadata:
  name: nvme-01
  namespace: mayastor
spec:
  node: kubeworker01
  disks:
    - /dev/disk/by-id/nvme-CT1000P3PSSD8_24514D0ACAF1

---
apiVersion: openebs.io/v1beta3
kind: DiskPool
metadata:
  name: nvme-02
  namespace: mayastor
spec:
  node: kubeworker02
  disks:
    - /dev/disk/by-id/nvme-WD_Blue_SN580_500GB_24455X411160
