apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-llama3-cache
  namespace: ai-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: zfs-ssd
  resources:
    requests:
      storage: 80Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-llama3-8b
  namespace: ai-platform
  labels:
    app: vllm
    model: llama3-8b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
      model: llama3-8b
  template:
    metadata:
      labels:
        app: vllm
        model: llama3-8b
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-GeForce-RTX-5070-Ti
      containers:
        - name: vllm
          image: vllm/vllm-openai:latest
          args:
            - "--model=meta-llama/Llama-3.1-8B-Instruct"
            - "--quantization=q5_k_m"
            - "--max-model-len=8192"
            - "--enable-chunked-prefill"
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "2"
              memory: 8Gi
              nvidia.com/gpu: 1
            limits:
              cpu: "4"
              memory: 16Gi
              nvidia.com/gpu: 1
          volumeMounts:
            - name: model-cache
              mountPath: /root/.cache/huggingface
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: vllm-llama3-cache
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-llama3
  namespace: ai-platform
spec:
  type: ClusterIP
  selector:
    app: vllm
    model: llama3-8b
  ports:
    - name: http
      port: 8000
      targetPort: 8000
