apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-api
  namespace: ai-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-api
  template:
    metadata:
      labels:
        app: agent-api
    spec:
      serviceAccountName: agent-api-ops
      containers:
        - name: agent-api
          image: docker.michaelhomelab.work/homelab-docker-repo/ai-platform/agent-api:0.4.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: agent-api-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
