apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
data:
  api-token: "Y2Z1dF92TVRXQk1qNDVMMmkxa2pLbVdSVXZOVkdwbHFSOTJ3SUFxOVpJRTBBNjQxYzYzZjQ="
