apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: ai-platform
data:
  config.yaml: |
    model_list:
      - model_name: "builder"
        litellm_params:
          model: "openai/Devstral-24B-v1-exl2-3_75"
          api_base: "http://builder.ai-platform.svc:8000/v1"
      - model_name: "analyst"
        litellm_params:
          model: "openai/Mistral-Small-24B-exl2"
          api_base: "http://analyst.ai-platform.svc:8000/v1"

    litellm_settings:
      drop_params: true
      set_verbose: true