apiVersion: v1
kind: Service
metadata:
  name: litellm
  namespace: ai-platform
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "4000"
spec:
  selector:
    app: litellm
  ports:
    - protocol: TCP
      port: 4000
      targetPort: http
      name: http
  type: ClusterIP
