apiVersion: apps/v1
kind: Deployment
metadata:
  name: raphael
  namespace: ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raphael
  template:
    metadata:
      labels:
        app: raphael
    spec:
      containers:
      - name: raphael
        image: docker.michaelhomelab.work/homelab-docker-repo/ai-agent/raphael:0.2.1
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "raphael-redis"
        - name: QDRANT_HOST
          value: "raphael-qdrant"
        - name: LLM_HOST
          value: "https://llm.michaelhomelab.work/v1"
        - name: LLM_KEY
          value: "sk-michael-homelab-llm-proxy"
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: raphael-secrets
              key: DISCORD_TOKEN
        - name: DISCORD_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: raphael-secrets
              key: DISCORD_WEBHOOK_URL
        - name: MENTION_ROLE_ID
          valueFrom:
            secretKeyRef:
              name: raphael-secrets
              key: MENTION_ROLE_ID
        - name: DISCORD_CHANNEL_ID
          value: "1314965373666549535"
        - name: DISCORD_GUILD_ID
          value: "1497901155634909276"
        - name: DISCORD_APP_ID
          value: "1497902452417237083"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
