apiVersion: v1
kind: Secret
metadata:
  name: raphael-secrets
  namespace: ai-agent
type: Opaque
data:
  DISCORD_TOKEN: TVRRNU5qazFOVE0zTmpZMk5UUTVNelV3TlEuR296Q21ULk9HQ2xJT2hMTTBPcHBMMnVkMDl4U0oxa3R5OXUwWXRCWHNxWmw0
