apiVersion: v1
kind: Secret
metadata:
  name: raphael-secrets
  namespace: ai-agent
type: Opaque
data:
  DISCORD_TOKEN: TVRRNU56a3dNalExTWpReE56SXpOekE0TXcuR0VBcThGLkJGOHNYb0RKV25Td3VjcHI3eEFSZElYOXM4X2dMWFh3NVBsVTdV
  DISCORD_WEBHOOK_URL: aHR0cHM6Ly9kaXNjb3JkYXBwLmNvbS9hcGkvd2ViaG9va3MvMTQ5NzkwMTQ3ODYzNDA2MTgyNS9VTXF4UndLS1ZqTEVPbHE0RkZaYXZ1WVl0dHFyMTlDSzRxRnQ0ZWtBMnFGNmMwdGNfbXRtYjFqeElLRlhjT0FfYk9xUw==
  MENTION_ROLE_ID: MTQ5Nzg1OTU2MjAyNjU2OTg5OQ==
