apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jevin
  namespace: ai-platform
spec:
  parentRefs:
    - name: nginx-gateway
      namespace: nginx-gateway
  hostnames:
    - jevin.michaelhomelab.work
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: jevin
          port: 8000
