apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: gateway-upload-policy
  namespace: nginx-gateway
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: nginx-gateway
  body:
    maxSize: "10G"
    timeout: 1800s
