apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sentinel/sentinel.yaml
  - sentinel/http-route.yaml
  - knowledge-chat/knowledge-chat.yaml
  - knowledge-chat/http-route.yaml
