apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ai-agent
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  description: "Ai agent platform"
  sourceRepos:
    - https://github.com/mike-homelab/homelab-k8s-platform
  destinations:
    - namespace: 'ai-agent'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
