apiVersion: apps/v1
kind: Deployment
metadata:
  name: research-agent
  namespace: ai-platform
  labels:
    app: research-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: research-agent
  template:
    metadata:
      labels:
        app: research-agent
    spec:
      containers:
        - name: research-agent
          image: docker.michaelhomelab.work/homelab-docker-repo/ai-platform/research-agent:0.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: VLLM_API_URL
              value: "http://agent-api:8000/v1/chat/completions"
            - name: EMBEDDING_API_URL
              value: "http://embedding-api:80/query"
---
apiVersion: v1
kind: Service
metadata:
  name: research-agent
  namespace: ai-platform
  labels:
    app: research-agent
spec:
  type: ClusterIP
  selector:
    app: research-agent
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
