apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-scaleset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: infrastructure
  source:
    chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: "0.14.2"
    helm:
      releaseName: arc-runner-set
      values: |
        githubConfigUrl: "https://github.com/mike-homelab/homelab-k8s-platform"
        githubConfigSecret: arc-github-secret
        runnerScaleSetName: "arc-runner-set"
        controllerServiceAccount:
          namespace: "arc-systems"
          name: "arc-gha-rs-controller"
        template:
          spec:
            containers:
              - name: runner
                image: ghcr.io/actions/actions-runner:latest
                command: ["/home/runner/run.sh"]
                env:
                  - name: DOCKER_HOST
                    value: unix:///run/docker/docker.sock
                volumeMounts:
                  - name: work
                    mountPath: /home/runner/_work
                  - name: docker-socket
                    mountPath: /run/docker
              - name: dind
                image: docker:dind
                command:
                  - /bin/sh
                  - -c
                  - |
                    dockerd --host=unix:///run/docker/docker.sock --host=tcp://0.0.0.0:2375 &
                    until [ -S /run/docker/docker.sock ]; do sleep 0.5; done
                    chmod 666 /run/docker/docker.sock
                    wait

                securityContext:
                  privileged: true
                env:
                  - name: DOCKER_TLS_CERTDIR
                    value: ""
                volumeMounts:
                  - name: work
                    mountPath: /home/runner/_work
                  - name: docker-socket
                    mountPath: /run/docker

            volumes:
              - name: work
                emptyDir: {}
              - name: docker-socket
                emptyDir: {}


  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

