# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: cert-manager-issuers
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/mike-homelab/homelab-k8s-platform
#     targetRevision: main
#     path: clusters/homelab/infra/cluster-issuer
#   destination:
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true

