apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    repoURL: https://nvidia.github.io/gpu-operator
    chart: gpu-operator
    targetRevision: 25.10.1
    helm:
      values: |
        operator:
          defaultRuntime: containerd

        driver:
          enabled: true

        toolkit:
          enabled: true

        devicePlugin:
          enabled: true
          config:
            create: true
            name: nvidia-time-slicing-config
            default: any
            data:
              any: |-
                version: v1
                sharing:
                  timeSlicing:
                    resources:
                    - name: nvidia.com/gpu
                      replicas: 1

              rtx-3060-config: |-
                version: v1
                sharing:
                  timeSlicing:
                    resources:
                    - name: nvidia.com/gpu
                      replicas: 2

        dcgmExporter:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
