apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    repoURL: https://nvidia.github.io/gpu-operator
    chart: gpu-operator
    targetRevision: 25.10.1
    helm:
      values: |
        operator:
          defaultRuntime: containerd

        driver:
          enabled: false

        toolkit:
          enabled: true

        devicePlugin:
          enabled: true

        dcgmExporter:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator

  syncPolicy:
    syncOptions:
      - CreateNamespace=true