apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-zfs-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/openebs/zfs-localpv
    targetRevision: v2.9.0   # latest stable release tag
    path: deploy             # directory containing CRDs + operator manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: zfs-csi
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    - Prune=false
