apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-zfs-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://openebs.github.io/openebs
    chart: zfs-localpv
    targetRevision: 2.6.0   # Helm chart version, not Git tag
  destination:
    server: https://kubernetes.default.svc
    namespace: zfs-csi      # ensure this matches your intended namespace
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    - Prune=false
