apiVersion: v1
kind: ConfigMap
metadata:
  name: kito-config
  namespace: kito
data:
  MINIO_ENDPOINT: "http://minio.monitoring.svc:9000"
  AZURE_SEARCH_ENDPOINT: "https://srch-tiko-prod.search.windows.net"
  LANGFUSE_HOST: "http://langfuse.ai-platform.svc:3000"
