apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault
  namespace: kito
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      vaultUrl: "https://kv-kito-prod.vault.azure.net"
      tenantId: "0af59592-b763-44a8-8f51-e9aabe8704a4"
      authSecretRef:
        clientId:
          name: azure-kv-creds
          key: client-id
        clientSecret:
          name: azure-kv-creds
          key: client-secret

