apiVersion: v1
kind: Service
metadata:
  name: kito-bot-service
  namespace: kito
spec:
  type: ClusterIP
  selector:
    app: kito-bot-service
  ports:
  - name: http
    port: 3000
    targetPort: http
