apiVersion: v1
kind: Service
metadata:
  name: kito-pdf-splitter
  namespace: kito
spec:
  type: ClusterIP
  selector:
    app: kito-pdf-splitter
  ports:
  - name: http
    port: 5000
    targetPort: http
