apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-crds
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/mike-homelab/homelab-k8s-platform
    targetRevision: main
    path: infrastructure/metallb/base/crds
  destination:
    server: https://kubernetes.default.svc
    namespace: default   # ignored for CRDs
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
