apiVersion: v1
kind: ServiceAccount
metadata:
  name: zfs-csi-sa
  namespace: zfs-csi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zfs-csi-role
rules:
- apiGroups: [""]
  resources: ["nodes","pods","persistentvolumes","persistentvolumeclaims","events"]
  verbs: ["get","list","watch","create","delete","update","patch"]

- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses","csinodes","csidrivers","volumeattachments"]
  verbs: ["get","list","watch","create","delete","update","patch"]

- apiGroups: ["zfs.openebs.io"]
  resources:
    - zfsnodes
    - zfsvolumes
    - zfssnapshots
    - zfsbackups
    - zfsrestores
  verbs: ["get","list","watch","create","delete","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zfs-csi-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zfs-csi-role
subjects:
- kind: ServiceAccount
  name: zfs-csi-sa
  namespace: zfs-csi
