apiVersion: v1
kind: Service
metadata:
  name: kito-artifact-generator
  namespace: kito
spec:
  type: ClusterIP
  selector:
    app: kito-artifact-generator
  ports:
  - name: http
    port: 5002
    targetPort: http
